### ISSUE TITLE
simpspector.yml path

### ISSUE THREAD

**Issue by dragonito** [simplethings/simpspector-analyser#2]
Looking for simpspector.yml in path where simpsector-command is used. In this time i´ve to specify the path with option -c

Example:

Root of project using:
../simpspector-analyser/simpspector ./

Not

../simpspector-analyser/simpspector -c simpspector.yml ./

Just have i look first to ./simspector.yml

**Comment by dragonito** [comment]
My fault you already changed it to .simpsector.yml

**Comment by DavidBadura** [comment]
:+1: :D everything else works?
